Repository abarichello/godot-ci, pull requests merged in 2024-10, with the labels that each got.

#156 Added 3.6 CI Version
  .github/workflows/godot-ci.yml
  .github/workflows/manual_build.yml
  .gitlab-ci.yml
  Dockerfile
  mono.Dockerfile
Labels: RELEASE

#149 Update for Godot 4.3
  .github/workflows/release.yml
  Dockerfile
  mono.Dockerfile
Labels: enhancement

#157 Fix invalid paths in GitHub Actions and GitLab CI workflow files
  .github/workflows/godot-ci.yml
  .gitlab-ci.yml
Labels: bug

#160 Fix actions: using upload-artifact@v4
  .github/workflows/godot-ci.yml
Labels: bug

#159 [4.3] Fix CI and Update Deprecated Step in Github Workflow
  .github/workflows/godot-ci.yml
  test-project/.gitignore
  test-project/default_env.tres
  test-project/export_presets.cfg
  test-project/icon.png.import
  test-project/project.godot
  test-project/resources/img/1.png.import
  test-project/resources/img/2.png.import
  test-project/resources/img/bullet-placeholder.png.import
  test-project/resources/img/cat0.png.import
  test-project/resources/img/coil.png.import
  test-project/resources/img/missile-placeholder.png.import
  test-project/scenes/Background.tscn
  test-project/scenes/Base.tscn
  test-project/scenes/Cannon.tscn
  test-project/scenes/EnemyGenerator.tscn
  test-project/scenes/GLOBAL.tscn
  test-project/scenes/HUD.tscn
  test-project/scenes/Main.tscn
  test-project/scenes/Player.tscn
  test-project/scenes/Projectile.tscn
  test-project/scripts/Cannon.gd
  test-project/scripts/EnemyGenerator.gd
  test-project/scripts/Main.gd
  test-project/scripts/Projectile.gd
Labels: bug
